spring:
  application:
    name: wms-movement
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  config:
    import: "wms-kafka.yml"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: wms-movement
      auto-offset-reset: earliest
      client-id: ${POD_NAME:local}
      enable-auto-commit: false

logging:
  level:
    org.apache.kafka: INFO
    org.springframework.kafka: INFO
      
management:
  otlp:
    metrics:
      export:
        enabled: ${MANAGEMENT_OTLP_METRIC_EXPORT_ACTIVE}
  tracing:
    enabled: ${MANAGEMENT_OTLP_TRACING_ACTIVE}