## GENERAL
POD_NAME: local

## KAFKA
KAFKA_BOOTSTRAP_SERVERS: localhost:9092
KAFKA_MOVEMENT_TOPIC: movement-topic

KAFKA_RETRY_TOPIC_ATTEMPTS: 3 #1 minium value, with 1 no retry topic will be created
KAFKA_RETRY_TOPIC_BACKOFF_DELAY: 1s
KAFKA_RETRY_TOPIC_BACKOFF_MULTIPLIER: 2
KAFKA_RETRY_TOPIC_BACKOFF_MAX_DELAY: 10s
KAFKA_DLT_TOPIC_SUFFIX: ".DLT"

## MANAGEMENT
MANAGEMENT_OTLP_METRIC_EXPORT_ACTIVE: false
MANAGEMENT_OTLP_TRACING_ACTIVE: false
